**`03_import_administrative_units`**

Import administrative units with geometries and create unique and consistent identifiers

In [1]:
%load_ext autoreload
%autoreload 2

# Administrative units identifiers
``openplaces`` organizes its data by ``admin_id`` (data class: ``AdminId``).

``admin_id`` is a geographical administrative index with hierarchical ``.levels`` of any depth.

- **0** - countries
- **1** - states/departments/...
- **2** - counties/municipalities/...
- **3** - subdivisions/towns/...
- **4** - neighborhoods/...
- **5** - ...

The initial built is derived from ISO and the Global Administrative Database (GADM).

In [2]:
from openplaces.core.schema import AdminId
admin_id = AdminId()
admin_id

AdminId(levels=())

## Start timer

In [3]:
from openplaces.timing import get_timer

timer = get_timer('import_admin', verbose=True)

# `admin0`: countries / territories
The highest level of the administrative hierarchy.
## ISO countries
Top-level administrative identifiers, gap-filled to match GADM, ships with `openplaces`

In [4]:
from openplaces.io.admin import get_admin0_iso
get_admin0_iso()

,name,admin0_id_a3,region,sub-region,intermediate-region
admin0_id,,,,,
AD,Andorra,AND,Europe,Southern Europe,
AE,United Arab Emirates,ARE,Asia,Western Asia,
AF,Afghanistan,AFG,Asia,Southern Asia,
AG,Antigua and Barbuda,ATG,Americas,Latin America and the Caribbean,Caribbean
AI,Anguilla,AIA,Americas,Latin America and the Caribbean,Caribbean
...,...,...,...,...,...
Z9,India - Z9,Z09,Asia,Southern Asia,
ZA,South Africa,ZAF,Africa,Sub-Saharan Africa,Southern Africa
ZM,Zambia,ZMB,Africa,Sub-Saharan Africa,Eastern Africa
ZN,Northern Cyprus,ZNC,Asia,Western Asia,
ZW,Zimbabwe,ZWE,Africa,Sub-Saharan Africa,Eastern Africa

## GADM countries
Example of how to download and ingest data from the Internet using a `recipe`:

In [5]:
from openplaces.recipe import get_recipe
from openplaces.utils import pretty_print
recipe = get_recipe(AdminId(), 'admin', source='admin0-gadm-4~1')
pretty_print(recipe)

admin_id:
  levels: []
entity:
  entity_type:
    entity_type: admin
  source:
    source_id: gadm
    url: https://geodata.ucdavis.edu/gadm/gadm4.1/gadm_410-levels.zip
    doi: null
  version: 4~1
compressed_file_name: gadm_410-levels.zip
uncompressed_file_name: gadm_410-levels.gpkg
layer: ADM_0
columns:
  name: COUNTRY
  admin0_id_a3: GID_0
compute_poi: true
index_function: openplaces.io.admin.index_from_admin0_id_a3
cache_filename: admin0
simplify_coverage_tolerance: 0.1

In [6]:
from openplaces.io.ingest import ingest_recipe
gdf = ingest_recipe(recipe, timer=timer)
gdf

Read file.....................................................     1.41s      1.38s cpu
Get latitude and longitude at WGS84 centroid..................     0.55s      0.55s cpu
Get centroids.................................................     3.20s      3.12s cpu
Get poles of inaccessibility..................................    68.51s     68.06s cpu
Save as parquet...............................................     3.83s      3.41s cpu
Creating simplified geometries. This can take some time.
Simplify coverage.............................................   140.27s    139.23s cpu
Save simplified coverage as geoparquet........................     0.17s      0.16s cpu

,name,admin0_id_a3,geometry,lat,long,ha,x_poi,y_poi,r_poi
admin0_id,,,,,,,,,
AD,Andorra,AND,"MULTIPOLYGON (((1.61725 42.62406, 1.63334 42.6...",42.543827,1.575209,4.510997e+04,1.571003,42.549513,12354.341219
AE,United Arab Emirates,ARE,"MULTIPOLYGON (((54.15408 22.75485, 54.14801 22...",23.915168,54.331973,7.109665e+06,54.503884,23.499402,87852.965141
AF,Afghanistan,AFG,"MULTIPOLYGON (((63.61554 29.4697, 63.61425 29....",33.828400,66.029590,6.438370e+07,66.295242,34.143003,380473.354995
AG,Antigua and Barbuda,ATG,"MULTIPOLYGON (((-61.67875 17.04097, -61.67875 ...",17.270961,-61.798268,4.358102e+04,-61.820694,17.068649,6247.352455
AI,Anguilla,AIA,"MULTIPOLYGON (((-63.02064 18.2075, -63.02587 1...",18.220412,-63.054860,7.988243e+03,-63.039015,18.226155,2786.076937
...,...,...,...,...,...,...,...,...,...
Z9,India,Z09,"MULTIPOLYGON (((78.90891 31.25886, 78.91309 31...",31.265201,79.077190,1.084614e+05,79.078220,31.260682,16406.616027
ZA,South Africa,ZAF,"MULTIPOLYGON (((19.66291 -34.78653, 19.66327 -...",-28.996293,25.086904,1.219710e+08,23.102874,-30.496958,434159.991011
ZM,Zambia,ZMB,"MULTIPOLYGON (((25.87834 -17.97218, 25.87034 -...",-13.457175,27.790374,7.511744e+07,26.177401,-14.828505,314049.723883
ZN,Northern Cyprus,ZNC,"MULTIPOLYGON (((33.10775 35.15992, 33.09934 35...",35.277828,33.599334,3.314061e+05,33.716618,35.220270,20073.450503
ZW,Zimbabwe,ZWE,"MULTIPOLYGON (((32.70425 -18.96022, 32.70537 -...",-19.000568,29.870843,3.900428e+07,29.940573,-18.837447,307798.048928

# ``admin1``: states / departments

## ISO states

In [7]:
from openplaces.io.admin import get_admin1_iso
get_admin1_iso()

                                  name admin0_id admin0_name
admin1_id_iso3166
AD-02                          Canillo        AD     Andorra
AD-03                           Encamp        AD     Andorra
AD-04                       La Massana        AD     Andorra
AD-05                           Ordino        AD     Andorra
AD-06              Sant Julia de Loria        AD     Andorra
...                                ...       ...         ...
ZW-MI                         Midlands        ZW    Zimbabwe
ZW-MN               Matabeleland North        ZW    Zimbabwe
ZW-MS               Matabeleland South        ZW    Zimbabwe
ZW-MV                         Masvingo        ZW    Zimbabwe
ZW-MW                 Mashonaland West        ZW    Zimbabwe

[3259 rows x 3 columns]

## GADM states

In [8]:
recipe = get_recipe(AdminId(), 'admin', source='admin1-gadm-4~1')
pretty_print(recipe)

admin_id:
  levels: []
entity:
  entity_type:
    entity_type: admin
  source:
    source_id: gadm
    url: https://geodata.ucdavis.edu/gadm/gadm4.1/gadm_410-levels.zip
    doi: null
  version: 4~1
compressed_file_name: gadm_410-levels.zip
uncompressed_file_name: gadm_410-levels.gpkg
layer: ADM_1
columns:
  admin1_id_gadm: GID_1
  admin1_id_hasc: HASC_1
  admin1_id_iso: ISO_1
  admin1_id_original: CC_1
  name: NAME_1
  name_original: NL_NAME_1
  name_alternatives: VARNAME_1
  type: ENGTYPE_1
  type_original: TYPE_1
  admin0_id_a3: GID_0
  admin0_name: COUNTRY
none_value: NA
compute_poi: true
set_index: admin1_id_gadm
cache_filename: admin1
simplify_coverage_tolerance: 0.1

In [9]:
gdf = ingest_recipe(recipe, timer=timer)

Read file.....................................................     1.60s      1.62s cpu
Get latitude and longitude at WGS84 centroid..................     0.30s      0.28s cpu
Get centroids.................................................     3.74s      3.73s cpu
Get poles of inaccessibility..................................    72.94s     72.33s cpu
Save as parquet...............................................     4.23s      3.81s cpu
Creating simplified geometries. This can take some time.
Simplify coverage.............................................   142.06s    141.02s cpu
Save simplified coverage as geoparquet........................     0.21s      0.20s cpu

In [10]:
gdf.sample(5).T

admin1_id_gadm,LKA.8_1,ARG.16_1,REU.3_1,MYS.15_1,CYM.4_1
admin1_id_hasc,LK.HB,AR.RN,RE.PL,MY.SL,KY.GT
admin1_id_iso,NA,NA,NA,MY-10,NA
admin1_id_original,NA,NA,NA,NA,NA
name,Hambantota,Río Negro,Saint-Paul,Selangor,George Town
name_original,NA,NA,NA,NA,NA
name_alternatives,NA,NA,NA,Selangor Darul Ehsan,NA
type,District,Province,Arrondissement,State,District
type_original,Distrikkaya,Provincia,Arrondissement,Negeri,District
admin0_id_a3,LKA,ARG,REU,MYS,CYM
admin0_name,Sri Lanka,Argentina,Réunion,Malaysia,Cayman Islands
geometry,MULTIPOLYGON (((80.93402862600004 6.0751400000...,MULTIPOLYGON (((-64.99986300099994 -42.0001369...,MULTIPOLYGON (((55.38013839700011 -21.28847312...,MULTIPOLYGON (((101.41976200000016 2.976621000...,MULTIPOLYGON (((-81.38291931099997 19.32668876...
lat,6.259761,-40.406632,-21.109235,3.270793,19.290881
long,81.097156,-67.228514,55.331322,101.498876,-81.359328
ha,260884.399298,20253963.087337,46533.929155,782449.445503,2892.974141
x_poi,81.120143,-67.252319,55.32408,101.500445,-81.367826
y_poi,6.294387,-40.442047,-21.07231,3.42869,19.28923
r_poi,12656.303294,223105.348234,9517.802438,26959.97376,1911.956599

In [15]:
timer.summary()
timer.save()

Timer: import_admin
Total: 444.85s

  Read file.................................................     1.41s      1.38s cpu (  0.3%)
  Get latitude and longitude at WGS84 centroid..............     0.55s      0.55s cpu (  0.1%)
  Get centroids.............................................     3.20s      3.12s cpu (  0.7%)
  Get poles of inaccessibility..............................    68.51s     68.06s cpu ( 15.4%)
  Save as parquet...........................................     3.83s      3.41s cpu (  0.9%)
  Simplify coverage.........................................   140.27s    139.23s cpu ( 31.5%)
  Save simplified coverage as geoparquet....................     0.17s      0.16s cpu (  0.0%)
  Read file.................................................     1.60s      1.62s cpu (  0.4%)
  Get latitude and longitude at WGS84 centroid..............     0.30s      0.28s cpu (  0.1%)
  Get centroids.............................................     3.74s      3.73s cpu (  0.8%)
  Get poles of inaccessibility..............................    72.94s     72.33s cpu ( 16.4%)
  Save as parquet...........................................     4.23s      3.81s cpu (  1.0%)
  Simplify coverage.........................................   142.06s    141.02s cpu ( 31.9%)
  Save simplified coverage as geoparquet....................     0.21s      0.20s cpu (  0.0%)
  _final....................................................     0.66s      0.58s cpu (  0.1%)